name: Build RifleLevel

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Xcode
        run: xcodebuild -project RifleLevel.xcodeproj -scheme RifleLevel -sdk macosx
